easy_admin:
    entities:
            # change the following to the namespaces of your own entities
            - App\Entity\Categories   
            - App\Entity\Produits
            - App\Entity\Pages
            - App\Entity\Utilisateurs
            - App\Entity\UtilisateursAdresses
            - App\Entity\Commandes
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
   